### PR TITLE
new redirects and file renames for consistency

### PR DESCRIPTION
**Pull request by MongoCaleb**
### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-NNNN

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodborg-staging.corp.mongodb.com/NNNNNNN/java/docsworker-xlarge/NNNNNNNNNNN/

### CODE REVIEW

**Review by cbush — APPROVED** [review]

**Review by nathan-contino-mongo — COMMENTED** [review]
Why the file name changes? I thought half the point of the new IA was to standardize some of these subtle differences that don't impact content?

**Review by nathan-contino-mongo — CHANGES_REQUESTED** [review]
I think you need to change the toc entries for those files if you rename them.

**Review by nathan-contino-mongo — APPROVED** [review]
I'm still not sure if I understand why we want to rename pages, but LG..TM?

**Comment by MongoCaleb** [comment]
> Why the file name changes? I thought half the point of the new IA was to standardize some of these subtle differences that don't impact content?

The file name changes are to match the others, not to differ from them. :)

**Pull request merged**
