### PR TITLE
(DOCSP-17258): June 30 2021 Release Notes

### PR DESCRIPTION
**Pull request by nathan-contino-mongo**
### Jira

- https://jira.mongodb.org/browse/DOCSP-17258

### Staged Changes (Requires MongoDB Corp SSO)

- [Release Notes - 06 30 2021](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-17258/release-notes/backend/#june-30-2021-release)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

### CODE REVIEW

**Review by mongomoe — APPROVED** [review]
LGTM 👍 , but any reason the text is kind of different from the JIRA ticket copy provided by Sumedha? Is that more of a rough outline rather than copy to follow verbatim?

**Comment by sumedham** [comment]
@nlarew - do we have the new CLI documented or ready to go sometime soon? If so, I think it would make a lot of sense to link to that here in the release notes, same with the github autodeploy improvements

**Comment by nlarew** [comment]
> @nlarew - do we have the new CLI documented or ready to go sometime soon? If so, I think it would make a lot of sense to link to that here in the release notes, same with the github autodeploy improvements

We have most schema commands documented in procedures but don't yet have a good page/section to link to that explains what the CLI is and provides reference docs for it. Hopefully we can get the generated CLI docs work rolling on the Realm side soon, but no ETA at this point.

**Comment by sumedham** [comment]
this LGTM, can we just pull out the CLI bullet? that one isn't ready yet for RC release yet

**Comment by nathan-contino-mongo** [comment]
@sumedham removed that bullet point, please give this an official github approval (in "Review Changes" in the "Files Changed" tab) for posterity.

**Review by sumedham — APPROVED** [review]

**Pull request merged**
